<a href="https://colab.research.google.com/github/RPAL-14/ML_LAB_ASSIGNMENT/blob/main/L1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Prerequisite**

In [ ]:
import numpy as np

# Question 1 - Basic NumPy Array

## (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]).

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


## (b) Flatten the NumPy array: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods.

In [ ]:
# Method 1: flatten
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array1 = array1.flatten()
print(flattened_array1)

# Method 2: ravel
flattened_array2 = array1.ravel()
print(flattened_array2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


## (c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])<br>
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(arr1, arr2)
print(are_equal)

True


## (d) Find the most frequent value and their indice(s) in the following arrays:
(i) x = np.array([1,2,3,4,5,1,2,1,1,1])<br>
(ii) y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
from collections import Counter
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_frequent_x = Counter(x).most_common(1)[0]
most_frequent_y = Counter(y).most_common(1)[0]
indices_x = np.where(x == most_frequent_x[0])[0]
indices_y = np.where(y == most_frequent_y[0])[0]

print(f"Most frequent value in x: {most_frequent_x[0]}, Indices: {indices_x}")
print(f"Most frequent value in y: {most_frequent_y[0]}, Indices: {indices_y}")

Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


## (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find:
i. Sum of all elements<br>
ii. Sum of all elements row-wise<br>
iii. Sum of all elements column-wise

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = gfg.sum()
sum_row_wise = gfg.sum(axis=1)
sum_column_wise = gfg.sum(axis=0)

print(f"Sum of all elements: {sum_all}")
print(f"Sum of all elements row-wise: {sum_row_wise}")
print(f"Sum of all elements column-wise: {sum_column_wise}")

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


## (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find:
i. Sum of diagonal elements<br>
ii. Eigen values of matrix<br>
iii. Eigen vectors of matrix<br>
iv. Inverse of matrix<br>
v. Determinant of matrix

In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Sum of diagonal elements
diagonal_sum = np.trace(n_array)

# ii. Eigen values of matrix
eigen_values = np.linalg.eigvals(n_array)

# iii. Eigen vectors of matrix
_, eigen_vectors = np.linalg.eig(n_array)

# iv. Inverse of matrix
inverse_matrix = np.linalg.inv(n_array)

# v. Determinant of matrix
determinant = np.linalg.det(n_array)

print(f"Sum of diagonal elements: {diagonal_sum}")
print(f"Eigen values of matrix: {eigen_values}")
print(f"Eigen vectors of matrix: \n{eigen_vectors}")
print(f"Inverse of matrix: \n{inverse_matrix}")
print(f"Determinant of matrix: {determinant}")

Sum of diagonal elements: 176
Eigen values of matrix: [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix: 
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix: 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


## (g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]], q = [[4, 5], [6, 7]]<br>
ii. p = [[1, 2], [2, 3], [4, 5]], q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
# Matrix Multiplication:
# First pair of matrices
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)

# Second pair of matrices
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
print(f"Product of first pair: \n{product1}")
print(f"Product of second pair: \n{product2}")


# Covariance:
covariance1 = np.cov(p1, rowvar=False)
covariance2 = np.cov(p2, rowvar=False)
print(f"Covariance of first matrix p1: \n{covariance1}")
print(f"Covariance of second matrix p2: \n{covariance2}")

Product of first pair: 
[[16 19]
 [26 31]]
Product of second pair: 
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance of first matrix p1: 
[[0.5 0.5]
 [0.5 0.5]]
Covariance of second matrix p2: 
[[2.33333333 2.33333333]
 [2.33333333 2.33333333]]


## (h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), find inner, outer and cartesian product.

In [ ]:
# Inner Product:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print(f"Inner product: \n{inner_product}")

# Outer Product:
outer_product = np.outer(x, y)
print(f"Outer product: \n{outer_product}")

# Cartesian Product (Note: Cartesian product is not a standard numpy operation, but you can use itertools):
import itertools
cartesian_product = np.array(list(itertools.product(x.flatten(), y.flatten())))
print(f"Cartesian product: \n{cartesian_product}")

Inner product: 
[[17 52]
 [13 62]]
Outer product: 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product: 
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


# Question 2 - NumPy Mathematics and Statistics

## (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

In [ ]:
# i. Find element-wise absolute value
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)

# ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row
flattened_array = array.flatten()
percentile_25 = np.percentile(flattened_array, 25)
percentile_50 = np.percentile(flattened_array, 50)
percentile_75 = np.percentile(flattened_array, 75)

percentile_25_column = np.percentile(array, 25, axis=0)
percentile_50_column = np.percentile(array, 50, axis=0)
percentile_75_column = np.percentile(array, 75, axis=0)

percentile_25_row = np.percentile(array, 25, axis=1)
percentile_50_row = np.percentile(array, 50, axis=1)
percentile_75_row = np.percentile(array, 75, axis=1)

print(f"25th percentile of flattened array: {percentile_25}")
print(f"50th percentile of flattened array: {percentile_50}")
print(f"75th percentile of flattened array: {percentile_75}")

print(f"25th percentile of each column: {percentile_25_column}")
print(f"50th percentile of each column: {percentile_50_column}")
print(f"75th percentile of each column: {percentile_75_column}")

print(f"25th percentile of each row: {percentile_25_row}")
print(f"50th percentile of each row: {percentile_50_row}")
print(f"75th percentile of each row: {percentile_75_row}")

# iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

mean_column = np.mean(array, axis=0)
median_column = np.median(array, axis=0)
std_column = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print(f"Mean of flattened array: {mean_flattened}")
print(f"Median of flattened array: {median_flattened}")
print(f"Standard Deviation of flattened array: {std_flattened}")

print(f"Mean of each column: {mean_column}")
print(f"Median of each column: {median_column}")
print(f"Standard Deviation of each column: {std_column}")

print(f"Mean of each row: {mean_row}")
print(f"Median of each row: {median_row}")
print(f"Standard Deviation of each row: {std_row}")

[[1 2 3]
 [4 5 6]]
25th percentile of flattened array: -3.5
50th percentile of flattened array: -0.5
75th percentile of flattened array: 2.5
25th percentile of each column: [-2.75 -0.25 -3.75]
50th percentile of each column: [-1.5  1.5 -1.5]
75th percentile of each column: [-0.25  3.25  0.75]
25th percentile of each row: [-0.5 -5. ]
50th percentile of each row: [ 1. -4.]
75th percentile of each row: [2.  0.5]
Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224
Mean of each column: [-1.5  1.5 -1.5]
Median of each column: [-1.5  1.5 -1.5]
Standard Deviation of each column: [2.5 3.5 4.5]
Mean of each row: [ 0.66666667 -1.66666667]
Median of each row: [ 1. -4.]
Standard Deviation of each row: [2.05480467 4.78423336]


## (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values.

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print(f"Floor values: {floor_values}")
print(f"Ceiling values: {ceiling_values}")
print(f"Truncated values: {truncated_values}")
print(f"Rounded values: {rounded_values}")

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


# Question 3 - Searching and Sorting

## (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453])
i. Sorted array<br>
ii. Indices of sorted array<br>
iii. 4 smallest elements<br>
iv. 5 largest elements

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.sort(array)[:4]
largest_5 = np.sort(array)[-5:]

print(f"Sorted array: {sorted_array}")
print(f"Indices of sorted array: {sorted_indices}")
print(f"4 smallest elements: {smallest_4}")
print(f"5 largest elements: {largest_5}")

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


## (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
i. Integer elements only<br>
ii. Float elements only

In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]
print(f"Integer elements only: {integer_elements}")
print(f"Float elements only: {float_elements}")

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


# Question 4

## (a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)

In [ ]:
import numpy as np
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)

    if len(img_array.shape) == 2:  # Grey Scale
        np.savetxt(r'/content/image_grey.txt', img_array, fmt='%d')
    else:  # RGB
        np.savetxt(r'/content/image_rgb.txt', img_array.reshape(-1, img_array.shape[2]), fmt='%d')

img_to_array(r'/content/Mountains.jpg')

## (b) Load the saved file into jupyter notebook?

In [ ]:
# For Grey Scale Image
# image_grey = np.loadtxt('/content/image_grey.txt', dtype=int)
# print(image_grey)

# For RGB Image
image_rgb = np.loadtxt('/content/image_rgb.txt', dtype=int)
image_rgb = image_rgb.reshape(-1, image_rgb.shape[1] // 3, 3)
print(image_rgb)

[[[ 38  37  53]]

 [[ 23  22  38]]

 [[ 34  32  46]]

 ...

 [[ 87 114 133]]

 [[ 93 120 139]]

 [[ 86 113 130]]]
